### ISSUE TITLE
const 依然存在！

### ISSUE THREAD

**Issue by hellobq** [jacob-lcs/react-webpack5-template#1]
配置了 @babel/preset-env 的 targets 属性值：

``` js
["@babel/preset-env", { "targets": { "ie": 11 } }]
```

打包后的 dist 产物依然存在 const 关键字：

![image](https://user-images.githubusercontent.com/29953650/142188481-cbd27d8e-f6f5-4da6-bf7b-05297f663226.png)

**Comment by jacob-lcs** [comment]
请在 webpack.common.js 中新增 `target: ['web', 'es5']`

**Comment by jacob-lcs** [comment]
具体如何修改可以查看这里：https://github.com/jacob-lcs/react-webpack5-template/blob/8a268a4447c511db7103a65d03d7eb3557fd9bde/webpack.common.js#L24
